name: flutter_dicas_cep_clean_architecture
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.4
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.9
  equatable: ^2.0.5
  mocktail: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  state_notifier_test: ^0.0.10
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
